# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraPlus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageimages',
            name='PictureLinkName',
            field=models.TextField(default=b'ok', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpageimages',
            name='DescText',
            field=models.TextField(default=0, max_length=600),
        ),
    ]
