# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraPlus', '0002_auto_20161118_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_ID', models.TextField(max_length=10)),
                ('Server_key', models.TextField(max_length=255)),
                ('Server_Name', models.TextField(max_length=50)),
                ('Server_Description', models.TextField(max_length=255)),
            ],
        ),
    ]
